### ISSUE TITLE
enable lightning on iris 6

### ISSUE THREAD

**Issue by donfox007** [keebio/keebio-firmware#3]
hey , 

i am verry happy with my prebuild - iris 6 and the via Support its amazing . 
but can you enable lightning  on the [https://github.com/keebio/keebio-firmware/blob/master/iris-r6/keebio_iris_rev6_via.hex](url) 

i think it's 
`qmk_backlight_rgblight` to the file 

greetings
P-J

**Comment by nooges** [comment]
See https://github.com/the-via/keyboards/issues/1128#issuecomment-1036314677
